[package]
name = "audiosnap"
version = "0.1.0"
authors = ["alamminsalo"]

[dependencies]
hound = "3.4.0"
clap = "2.31.2"
libc = "0.2.42"
lazy_static = "1.0.1"

[lib]
name = "audiosnap"
crate-type = ["staticlib"]
